cmake: Fix btf header missing in legacy kernel env.
When building C codes with cmake in legacy kernel environment,
compiler may failed to find `linux/btf.h` like this:
```
src/build/libbpf/bpf/btf.h:10:10: fatal error: linux/btf.h: No such file
or directory
^~~~~~~~~~~~~
compilation terminated.
```
This is because of missing `linux/btf.h` in system's header dirpaths.
So we need to include the uapi dir under libbpf as Makefile does.
By doing make install_uapi_headers together with install, we can let
both the kernel and user side compilers find these uapi headers.

Signed-off-by: Wuding Zeyu <woodpenker5@gmail.com>